### ISSUE TITLE
The Timeline with only Event Track not calling functions

### ISSUE THREAD

**Issue by igrir** [ddionisio/MateAnimator#14] opened 2015-10-20 06:52 UTC
Hi @ddionisio ! It's an awesome work you have to fork the Animator and keep the development running. Kudos to you!

I've found that if we have a timeline with only Event Track the functions only called once and the other keyframes after the first not called anymore.

For an example I've made a sequence of cinematic for moving camera with calling custom script I've made. First the camera move to point A and then move to point B. I used the Event Track and drag the object that has component script to control the camera. After played the game and set the keyframes to call the camera movement (with automatic play on start setting), only the first keyframe called.

The workaround for now is I have to create the Translation Track inside the timeline alongside the Event Track.

**Comment by ddionisio** [comment] 2015-10-20 07:49
Hi,

I'll look into it.  Sounds like when events are put into the sequencer of hotween, it needs tweens to happen within the timeline for them to get called.

**Comment by ddionisio** [comment] 2015-10-22 05:55
FYI, I'm looking to see if HOTween will be able to be fixed for Sequence to allow only callbacks and work as intended. (waiting for author's response)

**Comment by ddionisio** [comment] 2015-10-30 05:35
Should be fixed now.  Changed how events are handled.

**Closed by ddionisio** 2015-10-30 05:35 UTC
